services:
  mysql_db:
    image: mysql:8.0
    
    environment:
      MYSQL_ROOT_PASSWORD: dumi_password
      MYSQL_DATABASE: metodos_cuantitativos_dumi
      MYSQL_USER: dumi_user
      MYSQL_PASSWORD: dumi_password     
      
    ports:
      - "3306:3306"